name: Check output freshness

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: |
        npm install --prefix specification
        npm install --prefix typescript-generator

    - name: Generate output
      run: |
        npm run compile:canonical-json
        npm run compile:ts-validation

    - name: Check freshness
      run: |
        if [ -n "$(git status --porcelain)" ]; then echo Error: changes found after running documentation; git diff; git status; exit 1; fi
